Added info service and tests
TheReallyGreatTeamFSEMarch2021/Shamazin2 pull request #37
Opened 2021-03-12 21:24 UTC by jlavendtt

Added info repo
Added info service Layer
Added Info tests

2021-03-12 21:34 UTC, neveland98 approved these changes
Looks good. Thank you for testing your code before submitting it. :)

2021-03-12 21:45 UTC, timluu commented on src/main/java/com/talentpath/shamazin/showItemPage/services/InfoService.java
> +        else throw new NoSuchItemException("No item with id: " + id);
Do we have cases where an item is present with no info description? If so, NoSuchItemException and this message might not give an accurate representation of that error. If not, then we can just ignore my feedback

2021-03-12 21:46 UTC, timluu commented on src/test/java/com/talentpath/shamazin/showItemPage/services/ItemServiceTest.java
> +    }
What is this test for?

2021-03-12 21:47 UTC, timluu requested changes
One comment regarding the NoSuchItemException. If we ignore that though, everything else LGTM 👍🏻

2021-03-15 13:49 UTC, timluu approved these changes
lgtm

2021-03-15 13:50 UTC, merged