Feature starting spring sec
TheReallyGreatTeamFSEMarch2021/Shamazin2 pull request #63
Opened 2021-03-30 14:40 UTC by FeiYGH

2021-03-30 14:46 UTC, neveland98 requested changes
See comments

2021-03-30 14:46 UTC, neveland98 commented on src/main/java/com/talentpath/shamazin/showItemPage/controllers/AuthController.java
> +    public String testSec(){
make sure to remove testing code before merging into staging

2021-03-30 14:46 UTC, neveland98 commented on src/main/java/com/talentpath/shamazin/showItemPage/controllers/UserDataController.java
> +    public String testUserDataController(){
Make sure to remove testing code before merging.

2021-03-30 16:10 UTC, jaitken approved these changes
LGTM with Nathanial's comments

2021-03-31 18:15 UTC, neveland98 approved these changes

2021-03-31 19:18 UTC, merged